var express = require('express');  
var router = express.Router();
var client = require('./extra/connection.js');

client.index({  
  index: 'gov1',
  id: '1',
  type: 'constituencies',
  body: {
    "ConstituencyName": "If your company needs a unique domain, you can request for a domain here. You can login to SkilledTree$ your company logo. All your employees, recruiters and managers can see the new uploaded logo",
    "url": "CompanyBrand",
    "ConstituencyID": "CompanyBrand",
    "ConstituencyType": "/hr_managers/companybrand",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },  
  index: 'gov1',
  id: '2',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Before getting into SkilledTree, Add your teams in your company. This can be done in the ‘Settings’ page.SMS will be enabled by SkilledTree.You can write an Email to us. While adding employees, you might need to have the maximum SMS count. SMS total number of jobs posted by the HRs in your company.Total number of jobs assigned by the Hr Manager in your company and the total number of If the status of the referral candidates were not updated by you for about a week those total count will appear here.Total number of vacant Job positions.Resumes which are uploaded by employees in your company but are not tagged to recruiters by the Hr manager.Total number of referral resumes which are under the status of ‘Under Review’.After under reviewing the resumes if the candidates got shortlist.Total number of ShortListed resumes which are opted for further interview process will be interviewed by the assigned recruitersTotal number of Total number of rejected candidates in the interview process.Total number of resumes which are updated by the recruiters in the status",
    "url": "DashBoard",
    "ConstituencyID": "Dashboard",
    "ConstituencyType": "/hr_managers/dashboard",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
   index: 'gov1',
  id: '3',
  type: 'constituencies',
  body: {
    "ConstituencyName": "It’s a data visualization tool which helps you to get the complete details of the recruitment process and total number of jobs which are posted by you and the HR Managers in your team.Total number of jobs assigned by the Hr Manager in your company.If the status of the referral candidates were not updated by you for about a week those total count will appear here.Number of job positions to be entered while posting the job. Count denotes the total number of vacant job positions which are not filled. Open Referral Candidate Resumes which are uploaded by the employees in your team will be assigned to you for the interview process by your HR ManagCount denotes the total number of closed job positions. Closed Positions will be incremented once the positions are being filled. Closed positions will be taken by the status of the resumes. If the resume status is ‘Joined’, then it is considered as closed",
    "url": "DashBoard2",
    "ConstituencyID": "Dashboard2",
    "ConstituencyType": "/recruiter/dashboard",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '4',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Referral gifts and points which are added by the HR Manager will be listed in the dashboard. This displays is for your reference in order to earn the gifts accordingly",
    "url": "DashBoard3",
    "ConstituencyID": "Dashboard3",
    "ConstituencyType": "/employees/dashboard",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '5',
  type: 'constituencies',
  body: {
    "ConstituencyName": "You can apply to numerous amount of jobs which are suitable to your SkillSets. You can apply to the same In order to get more jobs, you need to connect with your friends as much as you can. So whenever their company posted any jobs, you will be get You can search any of the jobs which are posted by the members in your network whom you have connected with.Not only inside your network, You In order to apply to the job on behalf of your friend, you can apply it by uploading their resume. Automatically, SkilledTree will be created You can apply to the any job by clicking on the Job Title. It will redirect to the new tab along with the Job description",
    "url": "DashBoard4",
    "ConstituencyID": "Dashboard4",
    "ConstituencyType": "/friends/current_openings",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '6',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Find the Team UID in team page and send this team UID to all of employees of this team. You already know Each employee can sign up with team UID. Once employee signed up you can view the employees in view employees section and employee will job no$Create an account by youThere are two different ways to create an account for employees. One is upload a excel file and second one is manual.so setup an account for them Add multiple employees by CSV/ODS/XLS file Make sure that you have added team in the Team page. Employees list can be uploaded in the form of Click ‘Email List’ button in the ‘Add Employee’ section. Choose employees list file, team and click ‘Proceed’. Next page you will see preview Once you imported it may take few minutes to create accounts for them. Just wait few minute and refresh the ‘View employees’ section.Employees can be added manually by entering their FullName and Email/Phone. More than one employee can be added at a time by clicking the ‘Add To create employee account, you just navigate to ‘Employee’ section in left side menu and choose ‘Add Employee’.You can add employee ID while you create an account by manual for employee. And you can add employee ID by clicking ‘-’ in the ‘Emp Id’ section.If you want to move an employee from one team to another team, this can be possible by clicking team name of correspond employee in the the You can send login credentials to the employee if the employee has not yet joined SkilledTree or not yet received the credentials by clicking You can stay connected with any employees in the organization by clicking the chat icon in the View Employee page.Employees information can be deleted from the database when he/she resigned from the job by clicking the delete icon in the Employee ListThis ",
    "url": "Employees",
    "ConstituencyID": "Employees",
    "ConstituencyType": "/hr_managers/employees",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '7',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Make sure that you have added team in the ‘Settings’ page. Employees list can be uploaded in the form of as Employees can be added manually by uploading their Emp ID, Name, Email/Phone and Team He/She belongs to. More than one employee can be added as If you want to move an employee from one team to another team, this can be possible by clicking the editable dropdown in the Employees' List Employee ID can be edited by clicking the corresponding link in the Employee List.You can send login credentials to the employee if the employ$Employees information can be deleted from the database when he/she resigned from the job by clicking the delete icon in the List.You can stay connected with any employees in the organization by clicking the chat icon",
    "url": "Employees2",
    "ConstituencyID": "Employees2",
    "ConstituencyType": "/hr_managers/employees",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '8',
  type: 'constituencies',
  body: {
    "ConstituencyName": "It is a referral job networking site. In this site talent meets the talent hunters. Here professionals who want It is a site for professionals with different talents or skill sets. It is also works as a source of recruiting talented professionals through Only HR recruiters can create a job posting. If you are a HR of a company in need of some expert or fresher, you can post job. You need to create It is true that it a site for the professionals but with a big difference. It is no way something to chitchat, or update status. It is not have No, it is not possible directly. If you are in a circle of recruiters then only you come to know of the link. So be in connection.No, it is not possible directly. If you are in a circle of recruiters or in profile of the recruiters details is shared with connections There is no guarantee for a job from skilledTree. But generally everyone gets a referral job from the connection or notification for every new No, we do not guarantee a job to the jobless. This is only a referral job site. Here you create your connection with professionals and they Creating a profile in skilledTree does not mean that you will get a referral. It is up to your active presence and proper connection (networki Getting online here is for adding people in network. On the other hand, you may not find others online means you may have lesser number of constants relevancy is higher.While in other sites you can join anytime and start networking, in SkilledTree is all is through invitation. So you understand, if people like and HR recruiters can directly create account in this site. After creating their network they add employees and can invite others in SkilledTree to It is very helpful to source talented people. Without having to sort gems from the pile of stones, only relevant referral candidates are found and Yes, the subscription or membership to skilledTree very nominal charges than any other similar sites. You need to purchase subscription for ad Posting a job in SkilledTree is always beneficial in many ways. The most important reasons are.It is cost effective than other job portals as It is reliable as referrals come from employee circle not from anyone outside & unknown Relevancy of the candidates are higher as it is coming from referrals.It saves time as it is not bulk applications but a few genuine applicant It is very simple! When you source candidate from other places, you hardly know about them, except the resume. However, sourcing from SkilledTtee Getting online here is for finding referral job basically or to post jobs (for HRs). On the other hand, you may not find others online means you It is absolutely secure to share your profile and company information with us. But it is advised that you do not share anything personal or of SkilledTree is a referral job networking site. So here everything works with the primary idea of networking and referrals. Professionals join Yes, but recruiters only pay separately to people from whose connection chain a candidate has been selected, we do not involve ourselves in this First of all you are not manually referring anybody. People get notified of the job post available through you. They read and know about the just Actually you are not doing any referral manually. Everything is automatic. However, you can notify them personally to any post.Remember, they It is a networking that grows for referrals. The main reason of joining this network is to get referred to desired jobs. People only can join If you are serious about landing on the right organization that requires your talent, you have to accept invitation to join. More on that when Yes, you can but you have to keep in mind that this is not a socializing platform. This is purely a referral job networking site. So we request This network is to help people reach their desired or dreamt job via referrals. So the primary gain is the most suitable job. Besides this, why We believe in serious and genuine referral creation. So we have kept this network on invitation basis. So serious people would find out their",
    "url": "FAQ",
    "ConstituencyID": "FAQ",
    "ConstituencyType": "/faq",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '9',
  type: 'constituencies',
  body: {
    "ConstituencyName": "As you know that SkilledTree is multi level referral program. All of your company jobs will be reached to your friends and friends of friends if you added them here. Within your friends whoever interested for your company jobs they can easily apply without any activity of you.You don’t required to share referral opening to your friends as this is auto share to them once your friends added hereJobs will be auto shared to your friends through email, sms and mobile notification without any activity from you.You will receive referral bonus if any one of your friend got select Once you added friends, you always helping them to find better opportunity.Whenever your friends are added to SkilledTree by you, You will be getting some points. You can check your earned points in the DashYou can easily add your friends from Gmail, Hotmail and mobile contacts. Login to mobile app. Go to connection page and click red button, this is redirect you separate page. Click gmail or hotmail to add them",
    "url": "Friends",
    "ConstituencyID": "Friends",
    "ConstituencyType": "/employees/friends",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '10',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Employees will be rewarded based on the total earned points. By default few activities and its points will be added while signing up with SkilledTree. Changing the points to the certain activity is possible by clicking the editable points in the ‘Gamification’ section.By default, certain badges and points will be added. For e.g, If the employee reached 500 points by adding more friends, uploading referral candidate resumes etc.,he will be getting ‘Silver’ Badge. Whenever he is crossing certain points, he will be getting its badges accordingly",
    "url": "Gamification",
    "ConstituencyID": "Gamification",
    "ConstituencyType": "/hr_managers/gamification",
    "ValidVotes": 48694,
  },  
  index: 'gov1',
  id: '11',
  type: 'constituencies',
  body: {
    "ConstituencyName": "In the top right header, department which hr belongs to will be displayed. Next to that, your careers page link is added to the icon. You can visit your company’s career page by clicking on the link. And provided you can share this link to the referral candidates for job vacancies.SkilledTree messages help you to interact with applied candidates as well as with your employees. You can send a message to your employees and applied candidates. They will receive it in email and mobile app notifications.In the top right header, chat icon represents the conversation which you had previously with any of your colleagues by clicking it.It’s a complete help in reference to SkilledTree. You can read how SkilledTree works completely here.Major settings like Company profile, Your profile, Team, Resume status, domain will be added and modified here.You can set up your personal profile picture here. It will be visible to all your members in your network for better identification.You can reset your password even if you are not sure. It will be automatically popped up the current password. So you can reset it easily.If want to sign out the SkilledTree session",
    "url": "Header",
    "ConstituencyID": "Header",
    "ConstituencyType": "/hr_managers/header",
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '12',
  type: 'constituencies',
  body: {
    "ConstituencyName": "In the top right header, department which you belong to will be displayed. Next to that, your careers page link is added to the icon. You can visit your company’s career page by clicking on the link. And provided you can share this link to the referral candidates for job vacancies. ",
    "url": "Header2.html",
    "ConstituencyID": "Header2.html",
    "ConstituencyType": "/recruiter/header",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '13',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Conversations Chat icon represents the conversation which you had previously with any of your friends.It’s a complete help in reference to SkilledTree. You can read how SkilledTree works completely here.Major settings like Your profile,Password and notifications will be added and modified here.You can set up your personal profile picture here. It will be visible to all your members in your network for better identification.You can reset your password even if you are not sure. It will be automatically popped up the current password. So you can reset it easily",
    "url": "Header3",
    "ConstituencyID": "Header3",
    "ConstituencyType": "/employees/header",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '14',
  type: 'constituencies',
  body: {
    "ConstituencyName": "You can add your friends to SkilledTree by manually adding their details or by importing contacts from Gmail, Yahoo and Hotmail.Other members from various companies can give friend request to you. You can enlarge your members in your network by accepting it or reject it.Chat icon represents the conversation which you had previously with any of your friends.It’s a complete help in reference to SkilledTree. You can read how SkilledTree works completely here.Major settings like Your profile,Password and notifications will be added and modified here.You can set up your personal profile picture here. It will be visible to all your members in your network for better identification.You can reset your password even if you are not sure. It will be automatically popped up the current password. So you can reset it easily",
    "url": "Header4",
    "ConstituencyID": "Header4",
    "ConstituencyType": "/friends/header",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '15',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Your careers page link is added to the icon. You can visit your company’s career page by clicking on the link. And provided you can share this link to the referral candidates for job vacancies.It’s a complete help in reference to SkilledTree. You can read how SkilledTree works completely here.Major settings like Company profile, Your profile, Team, Resume status, domain will be added and modified here.You can set up your personal profile picture here. It will be visible to all your members in your network for better identification.You can reset your password even if you are not sure. It will be automatically popped up the current password. So you can reset it easily.If want to sign out the SkilledTree session",
    "url": "Header5",
    "ConstituencyID": "Header5",
    "ConstituencyType": "/hr_head/header",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '16',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Your careers page link is added to the icon. You can visit your company’s career page by clicking on the link. And provided you can share this link to the referral candidates for job vacancies.It’s a complete help in reference to SkilledTree. You can read how SkilledTree works completely here.Major settings like Company profile, Your profile, Team, Resume status, domain will be added and modified here.You can set up your personal profile picture here. It will be visible to all your members in your network for better identification.You can reset your password even if you are not sure. It will be automatically popped up the current password. So you can reset it easily.If want to sign out the SkilledTree session",
    "url": "Header6",
    "ConstituencyID": "Header6",
    "ConstituencyType": "/hr_regional/header",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '17',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Login career credentials will be sent to his email box once it’s added by the HR Head. Regional Managers can have multiple HR Managers under his region.He is devised to add the cities and assign HR Managers under those cities.He can go through all the referral resumes which are uploaded by the employees and undergo the employees list who are under various cities in his region.",
    "url": "HR Head",
    "ConstituencyID": "HR Head",
    "ConstituencyType": "/hr_head",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '18',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Each company has its own career page. This career page contains all the current open jobs. The purpose of this isHow can I include career page in our company website?In the top right header, next to your team name you will find second SkilledTree icon. Copy the link of this page and send it to your technical team. They will help to attach this link in your company website",
    "url": "HR Regional",
    "ConstituencyID": "HR Regional",
    "ConstituencyType": "/hr_regional",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '19',
  type: 'constituencies',
  body: {
    "ConstituencyName": "You can add cities in the ‘Add City’ in the side-menu. Cities can be edited by clicking on the editable city name. Make sure to give the city name as valid one while adding it.To create an account for HR Managers, all you need to do is to check whether the cities are added. Once it’s done, you can create HR Manager account by entering their Name, Email and his/her respective city under which he/she belongs. Login Credentials will be sent to the HR Manager once the account is set.HR Managers information will be listed below of the ‘HR Manager’ page. HR Managers can be added one at a time",
    "url": "HR Manager",
    "ConstituencyID": "HR manager",
    "ConstituencyType": "/hr_managers",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '20',
  type: 'constituencies',
  body: {
    "ConstituencyName": "The following are the major functionality that HR Manager can be opted for.Add employees by uploading employee(csv/xls) or by adding employee manually or by integrating Gmail,Yahoo & Hotmail contacts.Employee add friends by integrating Gmail,Yahoo,Hotmail contacts or by uploading friends list(csv/xls) or by manually entering email addresses.",
    "url": "HR Home",
    "ConstituencyID": "HR Home",
    "ConstituencyType": "/hr_managers",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '21',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Employees can add their friendly by uploading employee(csv/xls) or by adding employee manually or by If the company employees will be receiving the company rewards by performing the following activities.Employees will receive badges based on the activities they are performing such as. Friends Connection, Social Sharing, App Download, Selected Employees will receive badges based on the activities they are performing. Each activity will have certain badges such as Silver, Gold, Sapphi Employees will receive badges based on the activities they are performing. Each activity will have certain badges such as Gold coin, Silver",
    "url": "Employees Home",
    "ConstituencyID": "Employees home",
    "ConstituencyType": "/employees",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '22',
  type: 'constituencies',
  body: {
    "ConstituencyName": "The following are the major functionalities that the friends can be opted for.Employees can add their friends by uploading employee(csv/xls) or by adding employee manually or by integrating Gmail,Yahoo & Hotmail contacts.He can apply to a job refer his friends by uploading their resumes to the job he applied for.His status of the application can be notified by him via email Gem notification whenever it is updated by the concerned recruiter Friends can connect with other professionals on their network by maintaining the professional relationship with them.They can expand their network by accepting the friend request",
    "url": "Friends Home",
    "ConstituencyID": "Friends Home",
    "ConstituencyType": "/friends",
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '23',
  type: 'constituencies',
  body: {
    "ConstituencyName": "SkilledTree is multi level employee referral network. Your company referral job will be reached to all of your employees, employee friends and friends of friends. Here, there are three circle, first circle is all employees, second circle is all employee friends and third circle is friends of friends.Job notification will be reached to all members in the network. Any member in the network can apply the job and can recommend any of his friends.If any one of the candidate selected then employee who recommended will eligible to receive referral bonus from company if company has referral bonus policy. If company doesn’t has referral bonus policy this is not applicable for your company.SkilledTree tracks each employee referral activities, based on their activities SkilledTree adds points to them. Based on their points they are eligible for referral gifts. These gifts must be provided by your company. You can decide the types of gift and its points.Go to SkilledTree home page and click ‘Create Free Account’ button, and enter all the fields.This is a subdomain for your company. This create separate url for your company to access the SkilledTree.Suppose our company name is ‘Masymbol’. If I enter network name as ‘masymbol’ I would see our company url as 'masymbol.skilledtree.com’. All of our employees can access skilledtree as a ‘masymbol.skilledtree.com’ instead of skilledtree.com.You just set up referral amount in the company profile page. If your company provides referral bonus choose ‘As for policy’ or set ‘No rewards’.By default SkilledTree adds gamification feature to all company. If you would like disable this option to your company, go to company profile page and set Gamification as ‘disable’.First thing you need to do is setup account on SkilledTree. Once you setup the account you are ready to setup the multi level referral program for your company.Once you setup the account, app will create a default team for your company. This is like a team (group of employees) in your organization. Here, team is group of employees to receive relevant job notification.Create a sales team with all sales employees and create a another team (marketing) with marketing employees. And post a job for this sales team. Here, only your sales members will receive job notification but not your marketing members. So, all employees will receive only relevant job notification based his skillset.Purpose of the team is to send referral job notification to few members whom this job notification is relevant. This eliminate the irrelevant job notification to all employees.When you want add any employees in referral program, you must choose a team to add a employee. We recommend that not create more teams unless you really required it.You can create employee account using employee email/phone and their full name. If you have employees records in a XLS file, try to keep only two columns of full name and email/phone so it will easy to map with SkilledTree database records.Create separate employees list file for each team. Skilledtree only allow to upload separate employees list file for each team. You can’t upload multiple team members in a simple employees list. So, create separate employees list for each team to upload.To create employee account, you just navigate to ‘Employee’ section in left side menu and choose ‘Add Employee’To create multiple employee accounts you must have a xls / xlxs / cvs file with full name of each employee and their email/phone number. Click ‘Email List’ button in the ‘Add Employee’ section. Choose employees list file, team and click ‘Proceed’. Next page you will see preview of uploaded employee list, here you need to map the columns of employee list file with SkilledTree employee records. Map your employee list with SkilledTree records as below image and click ‘Import’ button.Once you imported it may take few minutes to create accounts for them. Just wait few minute and refresh the ‘View employees’ section. Note: Duplicate emails are not allowed. App simply discard those duplicate emails without creating an account.To create employee account, you just navigate to ‘Employee’ section in left side menu and choose ‘Add Employee’.Click ‘Employee Address’ button and in the pop up add employee full name, phone and choose team. If you want to add more than one employee click ‘Add More’ to add them. Once you added the employees click ‘Submit’.Once you added it may take few minutes to create accounts for them. Just wait few minute and refresh the ‘View employees’ section.Note: Duplicate emails are not allowed. App simply discard those duplicate emails without creating an account.Post a job, all of your current employees will receive job notification through email and SMS",
    "url": "Intro",
    "ConstituencyID": "Intro",
    "ConstituencyType": "/hr_managers/introduction",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '24',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Recruiters will be added by Hr Managers under specific team. The main responsibility of recruiter is to take up the recruitment process for the jobs which are posted in the network under his team. Few employees will be assigned under him. Referral candidate resumes which are uploaded by the employees will be listed in his ‘Resumes’ section. He can schedule the interview and update the application status for them. He can also do some activities such as adding employees to his team, posting the referral jobs, scheduling the interviews and updating the application statuses",
    "url": "Intro2",
    "ConstituencyID": "Intro2",
    "ConstituencyType": "/recruiter/introduction",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '25',
  type: 'constituencies',
  body: {
    "ConstituencyName": "SkilledTree is the portal for multi level employee referrals. All relevant jobs will be notified to employees and employees' friends and their friends. Here, job will reach three levels of circles (employees, employee friends and friends of friends).As an Employee, you can login to SkilledTree with the login credentials which was sent by your HR already to your Email Inbox / SMS. You will be moved to any team which was created and assigned by your employer. As an employee, you need to add your relevant friends to send job notification to them. Even your friend can add their friends. Whenever HR posts a job, all your friends will receive job notifications. Any of your friends applied or selected, you will receive referral bonus as per your company policy.SkilledTree recommends all the employees to use the mobile app instead of website as mobile app is simple to access, you will receive job notifications easily, you can easily recommend your friends and other candidates and many more functionalities are available which are easy to use.This is entirely automated. The main role of employee needs to do is, add his relevant friends to receive job notification. So, you don’t required to apply your friends resume instead your friend can apply.Jobs which are posted by the employers in your team will be visible in your jobs wall. You can add your friends who are job seekers or any working professionals to SkilledTree by uploading their personal information such as Name, Email or Phone number in an Excel format or by adding them manually.Else, you can share those jobs with any of your Social Media accounts such as Facebook, Twitter, LinkedIn, Pinterest and Google plus by integrating them",
    "url": "Intro3",
    "ConstituencyID": "Intro3",
    "ConstituencyType": "/employees/introduction",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '26',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Your friend has added you to the SkilledTree . You can login to SkilledTree with the login credentials which was sent by him already to your Email Inbox / SMS.The jobs which are posted by your friends will be visible in your jobs wall. You can apply or add your friends who are seeking the jobs or any working professionals to SkilledTree by uploading their personal information such as Name, Email or Phone number in an Excel format or by adding them manually. Those jobs will be reachable to them in their Jobs wall as well. Else, you can share those jobs with any of your Social Media accounts such as Facebook, Twitter, LinkedIn, Pinterest and Google plus",
    "url": "Intro4",
    "ConstituencyID": "Intro4",
    "ConstituencyType": "/friends/introduction",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '27',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Hr Head is the main resource who will plan and assign the branches of an organization into regional-wise. Furthermore, Regional HRs will split the HR Managers into city-wise. There will be only one HR Head to an organization.Dashboard.It’s a data visualization tool which helps you to get the complete details of the number of employees, number of cities, number of jobs posted and number of referral candidate resumes uploaded based on region-wise.Jobs which are posted in all the regions which you have created will be listed along with the department where the job belongs to, referral bonus details and job description. You can share those jobs in any of your social media accounts such as Facebook, LinkedIn, Twitter, Email Client etc., by clicking on the job title.You can check the resume repository that provides few details such as candidate name, job which they have applied, their skillset, the referrer who referred them and the date on which they have applied to the job for in the ‘Resumes’ page.You can check the employees list that provides few details such as Emp ID, Name of the employee, Team they belong to, number of their friends network, Last logged in date and their contact information",
    "url": "Intro5",
    "ConstituencyID": "Intro5",
    "ConstituencyType": "/hr_head/introduction",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '28',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Hr Head is the main resource who will plan and assign the branches of an organization into regional-wise. Furthermore, Regional HRs will split the HR Managers into city-wise. There will be only one HR Head to an organization.It’s a data visualization tool which helps you to get the complete details of the number of employees, number of cities, number of jobs posted and number of referral candidate resumes uploaded based on region-wise.Jobs which are posted in all the regions which you have created will be listed along with the department where the job belongs to, referral bonus details and job description. You can share those jobs in any of your social media accounts such as Facebook, LinkedIn, Twitter, Email Client etc., by clicking on the job title.You can check the resume repository that provides few details such as candidate name, job which they have applied, their skillset, the referrer who referred them and the date on which they have applied to the job for in the ‘Resumes’ page.You can check the employees list that provides few details such as Emp ID, Name of the employee, Team they belong to, number of their friends network, Last logged in date and their contact information",
    "url": "Intro6",
    "ConstituencyID": "Intro6",
    "ConstituencyType": "/hr_regional/introduction",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '29',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Recruiters should be added and assigned to a particular team before posting a job. While posting a Job, recruiters will be assigned to the job for the further recruitment process.It’s company policy that they can decide the referral amount to be given or no referral rewards for the referral jobs.This needs to be set before posting a job. It can be added in the ‘Company Profile’ under ‘Settings’ page.Once the team, recruiters and referral reward get fixed, you can able to post a job without any hassle. Jobs will be reachable to the team you have mentioned while posting the job and to the recruiters you have assigned under particular team.Mandatory fields are marked as with asterisk(*).Jobs can be closed automatically after 45 days from the date you posted. You can also close the jobs manually by clicking the ‘Trash’ Icon in case its needed.Closed Jobs can be reposted again with the same data you have entered before. Reposted Jobs will be reachable to the team you have mentioned while posting the job and to the recruiters you have assigned under the team.You can draft a job before posting it. Those Drafted jobs will be listed here and can be posted again at any point of time.Jobs can be searched with the fields listed in the table.You can search any job by clicking the ‘Search Job’ button in the Jobs page",
    "url": "Jobs",
    "ConstituencyID": "Jobs",
    "ConstituencyType": "/hr_managers/jobs",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '30',
  type: 'constituencies',
  body: {
    "ConstituencyName": "All the jobs posted by your recruitment team will be visible to you on jobs page. You can easily recommend any of your friends to each job by just adding their Share your referral job through your installed social media app like Whatsapp, facebook and others.Each job has recommend / apply button you can easily recommend any of your friends. All uploaded resumes by you will be visible in Resume page.If your friend’s profile is not matching with any of the posted jobs listed in your ‘Current Openings’ page, you can upload their resume irrespective of the job directly in the ‘Resumes’ page by clicking the ‘Upload Resume’ button.You can archive your friends resume and unarchive it later.You can search the resumes by entering any of the fields listed there in the table.You can download your friend’s resume",
    "url": "Jobs2",
    "ConstituencyID": "Jobs2",
    "ConstituencyType": "/recruiter/jobs",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '31',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Tweet a job If you were a working professional, you can tweet your company referral jobs. These jobs will be visible to your friends in your network.Jobs which are tweeted by you will be displayed here.If you want to know more about SkilledTree, how Job tweets will work then you can check it here by clicking on it.If any of your friends applied to your job tweet, you can track their details here",
    "url": "Job Tweets",
    "ConstituencyID": "Job Tweets",
    "ConstituencyType": "/friends/job_tweets",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '32',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Hr Head is devised to manage the general operation such as adding the regions and assigning HR Regional managers under each regions. This functionality can be enabled by the HR Managers in SkilledTree. Hr Head will receive the login credentials to his Email box. There will be only one HR Head in each company. HR Head can have multiple HR Regional Managers under the regions where he assigned them.Login credentials will be sent to his email box once it’s added by the HR Head. Regional Managers can have multiple HR Managers under his region.He is devised to add the cities and assign HR Managers under those cities.He can go through all the referral resumes which are uploaded by the employees and undergo the employees list who are under various cities in his region.As a HR Manager, he needs to be act as a single point of contact for internal recruiters, managers & employees. The major responsibilities for him are to add employees, add team, post job, add recruiters, assign recruiters, manage the referral resumes etc., There is an additional feature called ‘Gamification’. You can send a request to SkilledTree and this will be enabled instantly after being discussed. HR Manager can give admin access to any of his HR Recruiters by enabling it.HR Recruiters are someone who can handle the interview process and sending the feedback of the referrals to the HR Managers. They can take up the incharge of the recruitment process by assigning the job to themselves. HR Recruiters will not be having much functionalities like HR Managers. He will be allowed to do all the functions like HR Managers only if the admin access has been given to him. They can decide the suitable candidate and make them to get joined and send them out the rest by rejecting it.Employees will play the major role of referring their friends to the portal by adding them manually or by uploading their information in the form of Excel or by importing the contacts from Gmail, Yahoo and Outlook. They can track the status of their friends’ referral resumes.They will be receiving the referral reward if it is opted for them.Once their friends uploaded his/her resume, SkilledTree account will be created for them automatically. They can further apply to any number of jobs based on the required skills. They can refer their friends to any jobs by uploading their friends’ resume. As a working professional, he/she can tweet any referral job in his/her company.Add your employees and let them add their contacts. Now, your jobs will reach a massive number of job seekers with our multi level networking.A central repository for where you and your employees can upload resumes and store it for future recruitment. Each resume can be tagged with the respective skill sets.We have integrated various ways to add your employees and other prospects.You can upload an email list, add email addresses manually, use your email client to send invitations.You can track each applications received for each job posts, view profile of applicants, update the status of their applications and communicate with them using a messaging system.To motivate active participation, set up gamification to reward employees with points for certain activities. These points can be redeemed for gifts whenever employees wish.Add recruiters to the network. Whenever you posts a job, you can tag a recruiter to the job post so that they can carry out the recruitment process from the time candidates apply for the job",
    "url": "Main Page",
    "ConstituencyID": "Main Page",
    "ConstituencyType": "/",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '33',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Manager can only view the jobs and it’s resumes which are posted and assigned in his team. Manager can’t do all the activities like HRs instead he can view the resumes to screen them before scheduling an interview.Before adding manager, Make sure that you have added ‘Team’ in the ‘Settings’ section. ‘Default’ team is added when you create your organization account in SkilledTree. Name, Email and Team can be added by the HR Manager in the ‘Management’ section. One or more managers can be added at a single time by clicking ‘Add more’ button. Login credentials will be sent to his/her email client.You can search the recruiter by entering their email in the search box given there in ‘Recruiter’ under Management section.If you want to move a recruiter from one team to another team, this can be possible by clicking the editable dropdown in the Recruiter's List which is right below on ‘Recruiter’ section",
    "url": "Manager",
    "ConstituencyID": "Manager",
    "ConstituencyType": "/hr_managers/manager",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '34',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Add or Modify your profile details such as First name, Surname, Gender, Email ID, Phone Number, Passport, Date of Birth & Nationality for better identification in your network.Your High School and Higher Secondary School, UG and PG details are required to show your profile to the interviewer. So it is better to feed all those information in your profile section.Your key skills needs to be added.If you have your concern regarding the job, you can write it out here. It will also be visible to the interviewer.Information about your past employers, locations, employment dates, salaries, position held and duties held for a certain period should be noted.Previous projects you have done.Awards you got for your appreciation.Short term and long term achievements.Your strength can be added.Your Hobbies and Interests can be added.Your Social Media profile such as Facebook, LinkedIn or any other links can be added to contact you as well as to maintain a good relation",
    "url": "My Profile",
    "ConstituencyID": "My Profile",
    "ConstituencyType": "/friends/my_profile",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '35',
  type: 'constituencies',
  body: {
    "ConstituencyName": "SkilledTree will assign few referral gifts to each company account by default. These referral gifts are fully customizable by your HR manager. You will be getting the rewards incase your friends gets selected in the organization. Referral reward for each job will be decided by your company. And that will be processed by the corresponding HRs. You can track your referral reward status in the ‘Dashboard’.The jobs which are posted by the employers in your team will be visible in your jobs wall. You can add your friends who are seeking the jobs or any working professionals to SkilledTree by uploading their personal information such as Name, Email or Phone number in an Excel format or by adding them manually. Those jobs will be reachable to them in their Jobs wall. Else, you can share those jobs with any of your Social Media accounts such as Facebook, Twitter, LinkedIn, Pinterest and Google plus.Total number of points you have earned by performing various company activities such as Friends Connection, Upload Resume, Social Media Integration etc.,Bulk Points will be added to you if you refer any of your friends for the suitable job which was posted by uploading their resume in the ‘Resumes’ section",
    "url": "Points",
    "ConstituencyID": "Points",
    "ConstituencyType": "/employees/points_and_gifts",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '36',
  type: 'constituencies',
  body: {
    "ConstituencyName": "As you know that each team has multiple recruiters. These recruiters are going to handle your company recruitment activities. Each recruiter is responsible to complete the recruitment activities once after the resumes gets uploaded by the employees in SkilledTree.Recruiter can only see the assigned team jobs and its corresponded resumes and also he/she can post the jobs. He/She is the person who will schedule the interview and change the resume status of the applied candidates.Before adding recruiters, Make sure that you have added ‘Team’ in the ‘Settings’ section. ‘Default’ team is added when you create your organization account in SkilledTree. Name, Email/Phone and Team can be added by the HR Manager in the ‘Management’ section. One or more recruiters can be added at a single time by clicking ‘Add more’ button. If the recruiter has Email Id, Login credentials will be sent to his/her email client. SMS will be sent to recruiters if you entered their phone number.You can search the recruiter by entering their email in the search box given there in ‘Recruiter’ under Management section.HR Admin can perform all the functionality such as adding recruiters, managers, employees, team and posting jobs etc., In order to make recruiter as admin, give admin access by enabling the button ‘Give Admin Access’ in the Recruiter’s List. HR Admin Access can be revoked by clicking the same button again.You can send login credentials to the recruiter, if the recruiter has not yet joined SkilledTree or not yet received the credentials. He/She will be receiving either an Email or SMS.Recruiters will be deleted from the database when he/she resigned the job in your organization or can be deleted by manually",
    "url": "Recruiter",
    "ConstituencyID": "Recruiter",
    "ConstituencyType": "/hr_managers/recruiter",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },  
  index: 'gov1',
  id: '37',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Recruiters will be added by Hr Managers under specific team. The main responsibility of recruiter is to take up the recruitment process for the jobs which are posted in the network under his team. Few employees will be assigned under him. Referral candidate resumes which are uploaded by the employees will be listed in his ‘Resumes’ section. He can schedule the interview and update the application status for them. He can also do some activities such as adding employees to his team, posting the referral jobs, scheduling the interviews and updating the application statuses.",
    "url": "Recruiter Home",
    "ConstituencyID": "Recruiter Home",
    "ConstituencyType": "/recruiter",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '38',
  type: 'constituencies',
  body: {
    "ConstituencyName": "You can add regions in the ‘Add Region’ under ‘Add Hr Regional’. Regions can be edited by clicking on the editable region name. Make sure to give the region name as more understandable while adding it.Job notification will be reached to all members in the network. Any member in the network can apply the job and can recommend any of his friends.To create an account for HR Regional Managers, all you need to do is to check whether the regions are added. Once it’s done, you can create HR Regional Manager account by entering their Name, Email and his/her respective region under which he/she belongs. Login Credentials will be sent to the HR Regional Manager once the account is set.HR Regional Managers information will be listed below of the ‘HR Regional’ page. Regional Managers can be added one at a time",
    "url": "Regions",
    "ConstituencyID": "Regions",
    "ConstituencyType": "/hr_head/regions",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '39',
  type: 'constituencies',
  body: {
    "ConstituencyName": "You can view report for open jobs. It describes the status of all candidates.This graph describes the recruiters who are posted the jobs in your company.This graph describes the status of candidates for all jobs.These graphs describes the recruitment activities of each recruiters.Few information will be reported in the form of excel such as candidates in pipeline, Joined candidates, Rejected candidates, Employees with highest points and Team-wise total reach count with an extension of .xls.Few information will be reported in the form of excel such as candidates in pipeline, Joined candidates, Rejected candidates, Employees with highest points and Team-wise total reach count with an extension of .pdf .Bar graph will be drawn based on the HRs performance towards employee referral",
    "url": "Reports",
    "ConstituencyID": "Reports",
    "ConstituencyType": "/hr_managers/reports",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '40',
  type: 'constituencies',
  body: {
    "ConstituencyName": "You can view resumes belongs to each job in the jobs list page. Each job has a resume button on the right side bottom, click the ‘Resume’ you can view all the resumes applied for the job.Go to Resumes list page, here you can see all the open resumes. These all resumes classified with different categories. There are five categories of resumes. These are Employees Resumes directly uploaded by employees.Friends Resumes uploaded by employee friends.Friends of FriendsResumes uploaded by friends of friends.CareerResumes uploaded through your company career page.PublicResumes uploaded by candidates who is not a part of company network circles.Employees who uploaded their friend’s resume will come under ‘Employee Circle’.Similarly friends and their friends will come as ‘Friends’ & ‘Friends of Friends’. Candidates who have applied to any jobs from the ‘Careers’ page those resumes will come under ‘Careers’. If the Candidate applied to any public jobs which is on the left sidebar where he can search and apply to it, will come under ‘Public’.You can upload the resumes which was sent by your employees in ‘Upload Resume’ page.After reviewing / interviewing the candidates, you change their resume status in the ‘Resumes’ Section by clicking on the editable dropdown.Candidates Skills can be modified by the recruiters by changing the editable dropdown in the resumes repository list.HRs can archive the selected resume if they want. And they can unarchive it later by clicking on the UnArchive icon in the resumes list.If you want to move a recruiter from one team to another team, this can be possible by clicking the editable dropdown in the Recruiter's List which is right below on ‘Recruiter’ section.If you want to move a recruiter from one team to another team, this can be possible by clicking the editable dropdown in the Recruiter's List which is right below on ‘Recruiter’ section.If you want to move a recruiter from one team to another team, this can be possible by clicking the editable dropdown in the Recruiter's List which is right below on ‘Recruiter’ section.If you want to move a recruiter from one team to another team, this can be possible by clicking the editable dropdown in the Recruiter's List which is right below on ‘Recruiter’ section",
    "url": "Resumes",
    "ConstituencyID": "Resumes",
    "ConstituencyType": "/hr_managers/resumes",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '41',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Upload a candidate resume with the following information such as their resume, Candidate Name, Candidate Email/Phone, Skill Sets and the employee who referred the candidate by clicking the ‘Upload resume’ button in the Resumes section.This job will be assigned to you.After reviewing / interviewing the candidates, you change their resume status in the ‘Resumes’ Section by clicking on the editable dropdown.Candidates Skills can be modified by the recruiters by changing the editable dropdown in the resumes repository list.There are few default circles to upload resumes. Employees who uploaded their friend’s resume will come under ‘Employee Circle’.Similarly friends and their friends will come as ‘Friends’ & ‘Friends of Friends’. Candidates who have applied to any jobs from the ‘Careers’ page those resumes will come under ‘Careers’. If the Candidate applied to any public jobs which is on the left sidebar where he can search and apply to it, will come under ‘Public’.HRs can archive the selected resume if they want. And they can unarchive it later by clicking on the Archive icon in the resumes list.You can stay connected with any employees in the organization by clicking the chat icon.Resume Repository can be downloaded in the form of Excel. You can download the report by clicking on the ‘Download’ button which is beside to ‘Archive’. Downloaded Excel will be saved with the extension of xls.Assign a job which you posted in the editable job link in the editable dropdownYou can download any candidate’s resume for the interview process",
    "url": "Resumes2",
    "ConstituencyID": "Resumes2",
    "ConstituencyType": "/recruiter/resumes",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '42',
  type: 'constituencies',
  body: {
    "ConstituencyName": "If your friend’s profile is not matching with any of the posted jobs listed in your ‘Current Openings’ page, you can upload their resume irrespective of the job directly in the ‘Resumes’ page by clicking the ‘Upload Resume’ button.If your friend’s profile is not matching with any of the posted jobs listed in your ‘Current Openings’ page, you can upload their resume irrespective of the job directly in the ‘Resumes’ page by clicking the ‘Upload Resume’ button.If your friend’s profile is not matching with any of the posted jobs listed in your ‘Current Openings’ page, you can upload their resume irrespective of the job directly in the ‘Resumes’ page by clicking the ‘Upload Resume’ button.You can search the resumes by entering any of the fields listed there in the table.Whenever you share any jobs in any of your social media profiles such as Facebook, Twitter, LinkedIn, Pinterest and Google plus, you will receiving some points.Bulk Points will be added to you if you refer any of your friends for the suitable job which was posted by uploading their resume in the ‘Resumes’ section.Finally, you will be receiving the badges and the suitable gifts for your total earned points. And those points, badges and gifts are decided and given by your Employer. SkilledTree is not a part of this gamification activities",
    "url": "Resumes3",
    "ConstituencyID": "Resumes3",
    "ConstituencyType": "/employees/resumes",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '43',
  type: 'constituencies',
  body: {
    "ConstituencyName": "You can archive your friends resume from the list. You can unarchive it later.You can search the resumes by entering any of the fields listed there in the table.You can download any of your friend’s resume if it’s available",
    "url": "Resumes4",
    "ConstituencyID": "Resumes4",
    "ConstituencyType": "/friends/resumes",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '44',
  type: 'constituencies',
  body: {
    "ConstituencyName": "The process of dealing or managing the HR Recruiters, Employees and Managers and co-ordinating them for the better Employee Referral.Few of your personal details will be needed in order to make the better identification for members in your network such as the Email notification which will be sent in the background along with the login credentials while adding employees etc.,. Those information includes First name, last name, email ,phone number, designation and photo of yours.Company information is needed to create the belief in employees’ friends and their friends. And also it would be helpful for them to know about the company in a better way.‘Default’ Team can be added by default while creating the account in Skilledtree. You can add maximum of 3 teams to your company. After adding 3 teams, ‘Add Team ’ button will be disabled and If you need more teams, then you can raise a request to SkilledTree Admin regarding the same.In order to move the employees from one set of team to another, you can do it here. Select the ‘Source’ team and the ‘Destination’ team from the dropdown given. So all the employees under source team will be moved to the destination team.You can edit the name of the team by clicking on the corresponding edit pen icon in the list.You can edit the name of the team by clicking on the corresponding edit pen icon in the list.You can edit the name of the team by clicking on the corresponding edit pen icon in the list.Resume status such as Under Review, Short Listed, Interview, On Process, Selected, Rejected and Joined will be added by default. If you need some more statuses, you can add it here.You can reset your password even if you are not sure. It will be automatically popped up the current password. So you can reset it easily.If you don’t want to get any notifications from your team, you can unsubscribe it here. And if you want, you can enable it too.If you don’t want to get any job notifications, you can unsubscribe it here. And if you want, you can enable it too.If you don’t want to get any other notifications from SkilledTree, you can unsubscribe it here. And if you want, you can enable it too.If you want to hide your profile from search engine, you can enable/disable it here.We don’t want to leave you! But still if you were not satisfied or if you don’t want this product, you can delete your account here",
    "url": "Settings",
    "ConstituencyID": "Settings",
    "ConstituencyType": "/hr_managers/settings",
    "Electorate": 74499,
    "ValidVotes": 48694,
  }, 
  index: 'gov1',
  id: '45',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Few of your personal details will be needed in order to make the better identification for members in your network such as the Email notification which will be sent in the background along with the login credentials while adding employees etc.,. Those information includes First name, last name, email ,phone number, designation and photo of yours.Company information is needed to create the belief in employees’ friends and their friends. And also it would be helpful for them to know about the company in a better way.You can reset your password even if you are not sure. It will be automatically popped up the current password. So you can reset it easilyIf you don’t want to get any notifications from your team, you can unsubscribe it here. And if you want, you can enable it too.If you don’t want to get any job notifications, you can unsubscribe it here. And if you want, you can enable it too.If you don’t want to get any other notifications from SkilledTree, you can unsubscribe it here. And if you want, you can enable it too.If you want to hide your profile from search engine, you can enable/disable it here.We don’t want to leave you! But still if you were not satisfied or if you don’t want this product, you can delete your account here",
    "url": "Settings2",
    "ConstituencyID": "Settings2",
    "ConstituencyType": "/hr_head/settings",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '46',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Few of your personal details will be needed in order to make the better identification for members in your network such as the Email notification which will be sent in the background along with the login credentials while adding employees etc.,. Those information includes First name, last name, email ,phone number, designation and photo of yours.Company information is needed to create the belief in employees’ friends and their friends. And also it would be helpful for them to know about the company in a better way.You can reset your password even if you are not sure. It will be automatically popped up the current password. So you can reset it easily.If you don’t want to get any notifications from your team, you can unsubscribe it here. And if you want, you can enable it too.If you don’t want to get any job notifications, you can unsubscribe it here. And if you want, you can enable it too.If you don’t want to get any other notifications from SkilledTree, you can unsubscribe it here. And if you want, you can enable it too.If you want to hide your profile from search engine, you can enable/disable it here.If you want to hide your profile from search engine, you can enable/disable it here.We don’t want to leave you! But still if you were not satisfied or if you don’t want this product, you can delete your account here",
    "url": "Settings3",
    "ConstituencyID": "Settings3",
    "ConstituencyType": "/hr_regional/settings",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '47',
  type: 'constituencies',
  body: {
    "ConstituencyName": "Maximize your network by adding your friends as much as you can. So that you can share your resume for job reference in your friends company by selecting the contacts from the list.After enlarging your network, upload your resume in the ‘Profile’ section.Select the friends whom you want to share your resume for job recommendation. An Email will be sent to them along with your resume automatically.You can search any data within the fields in the table",
    "url": "Share Resumes",
    "ConstituencyID": "Share Resumes",
    "ConstituencyType": "/friends/share_resumes",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },
  index: 'gov1',
  id: '48',
  type: 'constituencies',
  body: {
    "ConstituencyName": "A team is group of employees in SkilledTree. While you post a job you need to choose a team. This job only visible to assigned team members but not other teams. So, each team member can see different jobs based his assigned team. This classifies all of your employees into different team.You can classify the team by skillset. For example, for all technology member create a team ‘technology’ and assign all technology members to this team. You can classify your teams by location or any other criteria you feel.When you setup an account SkilledTree creates one default team. And you assigned as recruiter for this default team.Each team can have multiple recruiters. You need to create new recruiter account for each recruiters. Recruiter can view only his assigned team jobs and resumes. This classifies the job visibility for recruiters. For more information look at the recruiter section.If you would like to create new team go to Team page and create a team. You can’t add more than 3 teams in your account. If you would like to add more team just contact SkilledTree support team to help you.Team UID is the unique ID of the team. Each team will possess a unique Team UID. This UID will be generated by the HR Manager in the ‘Team’ section under ‘Settings’. Once the UID is generated, it can’t be repeated again. This Team UID can be shared with the Employees in the organization. Employees can create ‘SkilledTree’ account by entering the Team UID which they have been provided in the registration page. Eventually, Employees who created the account with the Team UID will be grouped into new team",
    "url": "Team",
    "ConstituencyID": "Team",
    "ConstituencyType": "/hr_managers/team",
    "Electorate": 74499,
    "ValidVotes": 48694,
  },                          
       
},function(err,resp,status) {
    console.log(resp);
});